### ISSUE TITLE
Generating Your Code on My Server

### ISSUE THREAD

**Issue by scientifics** [sjl/stevelosh#3]

**Comment by sjl** [comment]
Hyde recently released a 2.0 version, but my site still uses the original.
Maybe that's the problem?

On 11/12, scientifics wrote:

> When I try to generate your code using hyde on my server (with no modifications) I get the following:
> 
> [sowens@web185 stevelosh]$ hyde gen
>  21:41:41 hyde.engine Reading site contents
>  21:41:41 hyde.engine Generating site at [/home/sowens/site/stevelosh]
>  21:41:41 hyde.engine Configuring the template environment
>  21:41:41 hyde.engine Generating site to [/home/sowens/site/stevelosh/deploy]
>  21:41:41 hyde.engine.Jinja2 Error parsing[skeleton/_atom.xml]
> Traceback (most recent call last):
>   File "/home/sowens/bin/hyde", line 8, in <module>
>     load_entry_point('hyde==0.8.4', 'console_scripts', 'hyde')()
>   File "/home/sowens/lib/python2.7/hyde/main.py", line 10, in main
>     Engine().run()
>   File "/home/sowens/lib/python2.7/hyde/engine.py", line 39, in run
>     super(Engine, self).run(args)
>   File "/home/sowens/lib/python2.7/commando.py", line 198, in run
>     args.run(self, args)
>   File "/home/sowens/lib/python2.7/hyde/engine.py", line 118, in gen
>     gen.generate_all(incremental=incremental)
>   File "/home/sowens/lib/python2.7/hyde/generator.py", line 205, in generate_all
>     self.__generate_node__(self.site.content, incremental)
>   File "/home/sowens/lib/python2.7/hyde/generator.py", line 303, in **generate_node**
>     self.**generate_resource**(resource, incremental)
>   File "/home/sowens/lib/python2.7/hyde/generator.py", line 318, in **generate_resource**
>     self.update_deps(resource)
>   File "/home/sowens/lib/python2.7/hyde/generator.py", line 144, in update_deps
>     deps.extend(self.template.get_dependencies(rel_path))
>   File "/home/sowens/lib/python2.7/hyde/ext/templates/jinja.py", line 725, in get_dependencies
>     deps.extend(self.get_dependencies(dep))
>   File "/home/sowens/lib/python2.7/hyde/ext/templates/jinja.py", line 716, in get_dependencies
>     ast = self.env.parse(text)
>   File "/home/sowens/lib/python2.7/jinja2/environment.py", line 394, in parse
>     self.handle_exception(exc_info, source_hint=source)
>   File "<unknown>", line 22, in template
> jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'recent_posts'. Jinja was looking for the following tags: 'endspaceless'. The innermost block that needs to be closed is 'spaceless'.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sjl/stevelosh/issues/3

## 

Steve Losh
